apps/libros/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, url
from .views import ListarLibros, RegistrarLibro, ActualizarLibro, EliminarLibro

"""
    Nota: Para cada elemento 'url' de 'urlpatterns' se debe tener en cuenta que el segundo argumento se
    indica de acuerdo a lo declarado en el view, ya que si las vista son declaradas con clases la sintaxis
    es clase.as_view() y si las vistas son declaradas con funciones entonces la sintaxis cambia a
    'ruta.del.views.funcion'
"""

urlpatterns = [
    #url(r'^', 'apps.libros.views.ListarLibros', name="listar_libros",),
    url(r'^listar_libros/$', 'apps.libros.views.ListarLibros', name="listar_libros",),
    url(r'^listar_libros_filtro/(?P<cod_sede>\w+)/(?P<cod_categoria>\w+)/(?P<cod_autor>\w+)/(?P<cod_editorial>\w+)/$', 'apps.libros.views.ListarLibrosFiltro', name="listar_libros_filtro",),
    url(r'^registrar_libro/', 'apps.libros.views.RegistrarLibro', name="registrar_libro",),
    url(r'^actualizar_libro/(?P<pk>\d+)/$', 'apps.libros.views.ActualizarLibro', name="actualizar_libro",),
    url(r'^eliminar_libro/(?P<pk>\d+)/$', 'apps.libros.views.EliminarLibro', name="eliminar_libro",),
    #url(r'^form_reporte_libro/$', 'apps.libro.views.FormReporteLibro', name="form_reporte_libro",),
    #url(r'^reporte_libro/(?P<libro>\d+)/$', 'apps.libro.views.ReporteLibro', name="reporte_libro"),
    #url(r'^busqueda_agremiado/$', 'apps.directiva.views.BuscarAgremiado', name='busqueda_agremiado',),
    #url(r'^nivel_cargo/$', 'apps.directiva.views.NivelCargo', name='nivel_cargo',),
    #url(r'^busqueda_directivo/$', 'apps.directiva.views.BuscarDirectivo', name='busqueda_directivo',),
    #url(r'^data/', 'apps.directiva.views.load_data', name="datos_electores",), # URL de Importación para la data
]

bva_libros/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework.routers import DefaultRouter
import settings

#router = DefaultRouter()
#router.register(r'registro', FichaPersonalViewSet)
urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'fumtea.views.home', name='home'),
                       url(r'^iniciar/', include('apps.login.urls')),
                       url(r'^libros/', include('apps.libros.urls')),
                       # Url direccion a la URL login
                       url(r'^$', 'apps.libros.views.home', name='home'),  # Url direccion a la URL login
                       url(r'^admin/', include(admin.site.urls)),
                       #url(r'^/', include(router.urls)),
                       url(r'^categorias/', include('apps.categorias.urls')),
                       url(r'^autores/', include('apps.autores.urls')),
                       url(r'^editoriales/', include('apps.editoriales.urls')),
                       url(r'^ejes/', include('apps.ejes.urls')),
                       url(r'^sedes/', include('apps.sedes.urls')),
                       url(r'^usuarios/', include('apps.login.urls')),
                       url(r'^bitacora/', include('apps.bitacora.urls')),
                       url(r'^foto/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^reporte/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PDF}),
                       )

apps/libros/models.py
# -*- encoding: utf-8 -*-
from django.db import models
#from apps.topologia.estados.models import Estado
#from apps.topologia.municipios.models import Municipio
#from apps.topologia.parroquias.models import Parroquia
from apps.categorias.models import Categoria
from apps.autores.models import Autor
from apps.editoriales.models import Editorial
from apps.sedes.models import Sede
from apps.bitacora.models import Bitacora
from django.contrib.auth.models import User


class Libros(models.Model):
    """
    Clase para el mantenimiento de los libros:
    Registrar, Modificar, Eliminar y Consultar

    :param CharField cod_libro: campo donde se registra el código del libro.
    :param CharField titulo: campo donde se registra el título del libro.
    :param CharField autor: campo donde se registra el autor del libro.
    :param DateField fecha_pub: campo donde se registra la fecha de publicación del libro.
    :param CharField editorial: campo donde se registra la editorial del libro.
    :param CharField categoria: campo donde se registra la categoría del libro.
    :param CharField sede: campo donde se registra la sede de ubicación del libro.
    """
    cod_libro = models.CharField(verbose_name="Código de libro", unique=True, max_length=15, null=True, blank=True)
    titulo = models.CharField(verbose_name="Título", max_length=200, null=True, blank=True)
    autor = models.ForeignKey(Autor, to_field='cod_autor', on_delete=models.SET_NULL, related_name='autor_libro', null=True)
    fecha_pub = models.DateField(verbose_name="Fecha de Publicación", null=True, blank=True)
    editorial = models.ForeignKey(Editorial, to_field='cod_editorial', on_delete=models.SET_NULL, related_name='editorial_libro', null=True)
    categoria = models.ForeignKey(Categoria, to_field='cod_categoria', on_delete=models.SET_NULL, related_name='categoria_libro', null=True)
    sede = models.ForeignKey(Sede, to_field='cod_sede', on_delete=models.SET_NULL, related_name='sede_libro', null=True)
    #Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    fecha_create = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    fecha_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True, blank=True)

    def __unicode__(self):
        # Método para retornar por defecto el valor de un campo especificado
        return self.titulo

apps/libros/forms.py
from django.forms import ModelForm
from django import forms
from apps.libros.models import Libros


class FormLibros(ModelForm):
    class Meta:
        model = Libros
        exclude = {'user', }

apps/libros/views.py
# -*- encoding: utf-8 -*-
import datetime
import time
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Bitacora
#from apps.topologia.estados.models import Estado
#from apps.topologia.municipios.models import Municipio
#from apps.topologia.parroquias.models import Parroquia
#from apps.registro.models import FichaPersonal
from .models import Categoria
from apps.autores.models import Autor
from apps.editoriales.models import Editorial
from .models import Sede
from .models import Libros
from .forms import FormLibros
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  # Paginacion
from django.contrib.auth.decorators import login_required  # Forma para impedir el acceso al sistema
from django.core import serializers
import unicodedata
import os
import csv
from django.db import connection
from django.db.models import Q
#import report_libro
#from apps.libro.reportes import report_libro


def home(request):
    return HttpResponseRedirect('/libros/listar_libros')

# Create your views here.
#@login_required(login_url='/iniciar/login/')
def ListarLibros(request):
    """
        Función para listar las líneas del estado. Se usa 'context_object_name' para enviar los registros del
        modelo a la vista especificada.

        :param estados: variable que contiene todos los objetos del modelo Estado.
        :param municipios: variable que contiene todos los objetos del modelo Municipio.
        :param parroquias: variable que contiene todos los objetos del modelo Parroquia.
        :param listar_libros: variable que contiene todos los objetos del modelo Libro.
    """
    categorias = Categoria.objects.all()
    autores = Autor.objects.all()
    editoriales = Editorial.objects.all()
    sedes = Sede.objects.all()
    #parroquias = Parroquia.objects.all()
    listar_libros = Libros.objects.all()
    ctx = {'listar_libros': listar_libros, 'categorias': categorias, 'sedes': sedes, 'autores': autores, 'editoriales': editoriales}  # ctx = Contexto
    return render_to_response('libros/lista.html', ctx, context_instance=RequestContext(request))
    

#@login_required(login_url='/iniciar/login/')
def ListarLibrosFiltro(request, cod_sede, cod_categoria, cod_autor, cod_editorial):
    """
        Función para listar las líneas del estado. Se usa 'context_object_name' para enviar los registros del
        modelo a la vista especificada.

        :param estados: variable que contiene todos los objetos del modelo Estado.
        :param municipios: variable que contiene todos los objetos del modelo Municipio.
        :param parroquias: variable que contiene todos los objetos del modelo Parroquia.
        :param listar_libros: variable que contiene todos los objetos del modelo Libro.
    """
    print "Codigo de la sede: ", cod_sede
    print "Codigo de la categoria: ", cod_categoria
    print "Codigo del autor: ", cod_autor
    print "Codigo de la editorial: ", cod_editorial
    categorias = Categoria.objects.all()
    autores = Autor.objects.all()
    editoriales = Editorial.objects.all()
    sedes = Sede.objects.all()
    
    # Preparamos un dicconario con los argumentos seleccionados desde el template
    parametros = {'sede_id':cod_sede, 'categoria_id':cod_categoria, 'autor_id':cod_autor, 'editorial_id':cod_editorial}
    
    condicion = ""
    
    contador = 0
    
    # Construimos la condicón de la consulta con los argumentos seleccionados desde el template
    for p in parametros:
		if parametros[p] != '0':
			contador += 1
			if contador > 1:
				condicion += " AND "+p+"='"+parametros[p]+"'"
			else:
				condicion = "WHERE "+p+"='"+parametros[p]+"'"
    
    print condicion
    
    #~ listar_libros = Libros.objects.filter(Q(sede_id=cod_sede)| Q(categoria_id=cod_categoria)| Q(autor_id=cod_autor)| Q(editorial_id=cod_editorial))  # No es de utilidad en este caso
    listar_libros = Libros.objects.raw("SELECT * FROM libros_libros "+condicion)
    #~ 
    print listar_libros
    
    ctx = {'listar_libros': listar_libros, 'categorias': categorias, 'sedes': sedes, 'autores': autores, 'editoriales': editoriales}  # ctx = Contexto
    return render_to_response('libros/lista.html', ctx, context_instance=RequestContext(request))


@login_required(login_url='/iniciar/login/')
def RegistrarLibro(request):  # Forma actual
    """
        Función para registrar una libro de un estado.

        :param estados: variable que contiene todos los objetos del modelo Estado.
        :param municipios: variable que contiene todos los objetos del modelo Municipio.
        :param parroquias: variable que contiene todos los objetos del modelo Parroquia.
        :param num_libros: variable que contiene el código generado para la nueva línea.
        :param reg_bitacora: variable que contiene la asignación de un nuevo registro al modelo Bitacora.
    """
    num_libros = Libros.objects.count()  # Número de circuitos registrados
    # Conversión del números de circuitos anteponiendo ceros a la izquierda hasta alcanzar el límite de 4 dígitos
    num_libros = "L"+str(num_libros+1).zfill(4)
    categorias = Categoria.objects.all()
    autores = Autor.objects.all()
    editoriales = Editorial.objects.all()
    sedes = Sede.objects.all()
    #municipios = Municipio.objects.all()
    #parroquias = Parroquia.objects.all()
    if request.method == 'POST':
        #print "DATOS: ", request
        from_rlibro = FormLibros(request.POST, request.FILES)
        if from_rlibro.is_valid():
            nuevo_rlibro = from_rlibro.save(commit=False)
            nuevo_rlibro.user = request.user.username
            nuevo_rlibro.save()
            x = datetime.datetime.now()
            #print "Fecha y Hora: "+str(x)
            #acc = "Registro de nueva línea: "+request.POST['libro']+"..."
            acc = "Registro de nuevo libro ("+str(request.POST['cod_libro'])+")..."
            #print acc
            reg_bitacora = Bitacora(
                accion=acc,
                usuario=request.user.username,
                fecha=x,)
            reg_bitacora.save()
            return HttpResponseRedirect('/libros/listar_libros')
    else:
        from_rlibro = FormLibros()
    ctx = {'from_rlibro': from_rlibro, 'cod_libro': num_libros, 'categorias': categorias, 'sedes': sedes, 'autores': autores, 'editoriales': editoriales}  # ctx = Contexto (datos de los modelos)
    return render_to_response('libros/nuevo_libro.html', ctx, context_instance=RequestContext(request))


@login_required(login_url='/iniciar/login/')
def ActualizarLibro(request, pk):
    """
        Función para editar los datos de una línea

        :param estados: variable que contiene todos los objetos del modelo Estado.
        :param municipios: variable que contiene todos los objetos del modelo Municipio.
        :param parroquias: variable que contiene todos los objetos del modelo Parroquia.
        :param obj_rlibro: variable que contiene el objeto del modelo Libro que coincide con el id dado.
        :param reg_bitacora: variable que contiene la asignación de un nuevo registro al modelo Bitacora.
    """
    #estados = Estado.objects.all()
    obj_rlibro = Libros.objects.get(id=pk)
    categorias = Categoria.objects.all()
    autores = Autor.objects.all()
    editoriales = Editorial.objects.all()
    sedes = Sede.objects.all()
    if request.method == 'POST':
        form_rlibro = FormLibros(request.POST, request.FILES, instance=obj_rlibro)
        if form_rlibro.is_valid():
            edit_rdirectivo = form_rlibro.save(commit=False)
            edit_rdirectivo.user = request.user.username
            edit_rdirectivo.save()
            x = datetime.datetime.now()
            #print "Fecha y Hora: "+str(x)
            reg_bitacora = Bitacora(
                accion="Actualización del libro '"+str(request.POST['cod_libro'])+"'...",
                usuario=request.user.username,
                fecha=x,)
            reg_bitacora.save()
            return HttpResponseRedirect('/libros/listar_libros')
    else:
        form_rlibro = FormLibros(instance=obj_rlibro)
    ctx = {'form_rlibro': form_rlibro, 'obj_rlibro': obj_rlibro, 'categorias': categorias, 'sedes': sedes, 'autores': autores, 'editoriales': editoriales}  # ctx = Contexto
    return render_to_response('libros/editar_libro.html', ctx, context_instance=RequestContext(request))


@login_required(login_url='/iniciar/login/')
def EliminarLibro(request, pk):
    """
        Función para eliminar una línea. Se usa 'context_object_name' para enviar el registro del modelo
        a la vista especificada.

        :param obj_rlibro: variable que contiene el objeto del modelo Libro que coincide con el id dado.
        :param x: variable que contiene la fecha y hora actual.
        :param reg_bitacora: variable que contiene la asignación de un nuevo registro al modelo Bitacora.
    """
    obj_rlibro = Libro.objects.get(id=pk)
    obj_rlibro.delete()
    x = datetime.datetime.now()
    #print "Fecha y Hora: "+str(x)
    reg_bitacora = Bitacora(
        accion="Eliminación de la línea '"+str(obj_rlibro.cod_libro)+"'...",
        usuario=request.user.username,
        fecha=x,)
    reg_bitacora.save()
    return HttpResponseRedirect('/libro/listar_libros')


#@login_required(login_url='/iniciar/login/')
#def FormReporteLibro(request):
#    """
#    Función para generar una vista para la selección de una línea de moto taxis específica. Se usa 'context_object_name' para enviar el registro del modelo
#    a la vista especificada.
#    """
#    listar_libros = Libro.objects.all()
#    ctx = {'listar_libros': listar_libros}  # ctx = Contexto
#    return render_to_response('libro/reporte_libro.html', ctx, context_instance=RequestContext(request))
#
#

templates/libros/editar_libro.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block title %}Actualizar Libro{% endblock title%} <!--Bloque para definir el título-->



{% block contenido %} <!-- Apertura de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2-bootstrap.css">
	
<script src="{{STATIC_URL}}js/select2/select2.js"></script>
<script src="{{STATIC_URL}}js/select2/select2_locale_es.js"></script>
<script>
	$(document).ready(function() {
		$("select").select2();
		$("#id_configuracion").attr('class','active');
		$('#id_linea').alpha({allow: " "});
		$('#id_presidente').alpha({allow: " "});
		$('#id_telefono').numeric({allow: ""}).attr('maxlength','11');
	});
</script>
<script type="text/javascript">
$(document).ready(function(){
	$('#titulo').numeric(); //Valida solo valores tipo texto
	$('#autor').alpha({allow:" "}); //Valida solo valores tipo texto
	$('#id_apellidos').alpha({allow:" "}); //Valida solo valores tipo texto
	$('#id_telefono').numeric(); //Valida solo valores tipo texto
	$('#id_nacionalidad').select2();
	
	// Pre-selección de opciones
	$("#autor").select2('val',$("#id_autor").val());
	$("#editorial").select2('val',$("#id_editorial").val());
	$("#categoria").select2('val',$("#id_categoria").val());
	$("#sede").select2('val',$("#id_sede").val());
	
	// Aplicación de bootstrap-datepicker
	//var startDate = new Date('01/01/2015');
	var FromEndDate = new Date();
	var ToEndDate = new Date();
	
	ToEndDate.setDate(ToEndDate.getDate()+365);
	
	$('#fecha_pub').datepicker({
	  format: "dd/mm/yyyy",
	  //endDate: FromEndDate,
	  language: "es",
	  autoclose: true,
	})
	
	//$("#id_cedula").change(function() {
	//    $.get('/fiscales/buscar/', {'cedula': $('#id_cedula').val(), 'bandera': 'true'}, function (response) {
	//		if (response == 'existe') {
	//			bootbox.alert("Disculpe, la cédula ya existe...", function () {
	//			$('#id_cedula').val("");
	//			$("#id_nombres").val("")
	//			$("#id_apellidos").val("")
	//			$('#id_cedula').parent('div').addClass('has-error');
	//			});
	//		}
	//    });
	//});
	    
	// Validamos los campos del formulario
	$("#actualizar").click(function(e) {
	   e.preventDefault();  // Para evitar que se envíe por defecto
		    
	    if($('#titulo').val().trim() == ''){
		bootbox.alert("Rellene el campo de título", function () {
		$('#titulo').parent('div').addClass('has-error');
		});
		$('#titulo').focus();
	    }else if($('#autor').val().trim() == ''){
		bootbox.alert("Rellene el campo de autor", function () {
		$('#autor').parent('div').addClass('has-error');
		});
		$('#autor').focus();
	    }else if($('#fecha_pub').val().trim() == ''){
		bootbox.alert("Rellene el campo de fecha", function () {
		$('#fecha_pub').parent('div').addClass('has-error');
		});
		$('#fecha_pub').focus();
	    }else if($('#editorial').val().trim() == ''){
		bootbox.alert("Rellene el campo de editorial", function () {
		$('#editorial').parent('div').addClass('has-error');
		});
		$('#editorial').focus();
	    }else if ($('#categoria').val() == '0') {
		bootbox.alert("Seleccione la categoría", function () {
		$('#categoria').parent('div').addClass('has-error');
		});
		$('#categoria').focus();
	    }else if ($('#sede').val() == '0') {
		bootbox.alert("Seleccione la sede", function () {
		$('#sede').parent('div').addClass('has-error');
		});
		$('#sede').focus();
	    }else{
		$('#form_libro').submit();
		}
	});
	
	$('#volver').click(function(){
	    url = '/libros/listar_libros'
	    window.location = url
	})
	
});
</script>
    <form method="post" id="form_libro">
	{% csrf_token %}
	<div class='panel panel-default' style='width:60%'>
		    <div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Actualizar libro</div>
		    <br>
	<table style="text-align:center;border-collapse: separate;border-spacing: 5px 15px;">
        <tr>
            <td>Título:</td>
			<td>
				<input id="cod_libro" name="cod_libro" type="hidden" value="{{obj_rlibro.cod_libro}}"/>
				<input id="titulo" required name="titulo" type="text" value='{{obj_rlibro.titulo}}'/>
			</td>
	    </tr>
	    <tr>
			<td>Autor:</td>
			<td>
				<select id='autor' name='autor'>
				<option value='0'>-----------------</option>
				{% for au in autores %}
				<option value='{{au.cod_autor}}'>{{au.autor}}</option>
				{% endfor %}
				</select>
			</td>
	    </tr>
	    <tr>
			<td>Fecha de publicación:</td>
			<td>
				<input id="fecha_pub" name="fecha_pub" type="text" value='{{obj_rlibro.fecha_pub |date:"SHORT_DATE_FORMAT"}}'/>
			</td>
	    </tr>
	    <tr>
			<td>Editorial:</td>
			<td>
				<select id='editorial' name='editorial'>
				<option value='0'>-----------------</option>
				{% for ed in editoriales %}
				<option value='{{ed.cod_editorial}}'>{{ed.editorial}}</option>
				{% endfor %}
				</select>
			</td>
	    </tr>
	    <tr>
			<td>Categoría:</td>
			<td>
				<select id='categoria' name='categoria'>
				<option value='0'>-----------------</option>
				{% for c in categorias %}
				<option value='{{c.cod_categoria}}'>{{c.categoria}}</option>
				{% endfor %}
				</select>
			</td>
	    </tr>
		<tr>
			<td>Sede:</td>
			<td>
				<select id='sede' name='sede'>
				<option value='0'>-----------------</option>
				{% for s in sedes %}
				<option value='{{s.cod_sede}}'>{{s.sede}}</option>
				{% endfor %}
				</select>
			</td>
	    </tr>
			<input type='hidden' id="id_user_create" name="user_create" value='{{obj_reje.user_create.id}}'/>
			<input type='hidden' id="id_user_update" name="user_update" value='{{user.id}}'/>
			<input type='hidden' id="id_autor" value='{{obj_rlibro.autor}}'/>
			<input type='hidden' id="id_editorial" value='{{obj_rlibro.editorial}}'/>
			<input type='hidden' id="id_categoria" value='{{obj_rlibro.categoria}}'/>
			<input type='hidden' id="id_sede" value='{{obj_rlibro.sede}}'/>
	    <tr>
			<td colspan='2'>
				<input type="submit" id="actualizar" value="Actualizar"/>
				<input type="button" id="volver" value="Volver" class="btn btn-primary"/>
			</td>
	    </tr>
	</table>
</div>
    </form>
{% endblock contenido %} <!-- Cierre de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->

templates/libros/reporte_linea.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->
    {% block title %}Reporte de línea{% endblock title%}
    {% if form.non_field_errors %}
    <div class="panel">
      {{ form.non_field_errors }}
    </div>
  {% endif %}
  {% block contenido %}
  <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2-bootstrap.css">
	
<script src="{{STATIC_URL}}js/select2/select2.js"></script>
<script src="{{STATIC_URL}}js/select2/select2_locale_es.js"></script>
    <script>
	  $(document).ready( function () {
	  	$("select").select2();
		$("#id_reportes").attr('class','active');
		
		$("#reporte_linea").click(function() {
		  var linea = $("#id_linea").val();
		  
		  //alert(linea)
			 
		  if (linea != '') {
			URL = "../reporte_linea/"+linea
			window.open(URL)
		  }else{
            apprise("Seleccione una línea");
            return false;
          }
		
		});
		  
	  } );
	  		
	</script>
	<br><br><br><br>
    <table style="text-align:center;border-collapse: separate;border-spacing: 5px 15px;">
	  <tr>
		<td colspan="2" style='background-color:#B1ACA5;color:white;text-align:center;'>
		  Reporte de agremiados por línea
		</td>
	  </tr>
	  <tr>
		<td>Línea:</td>
		<td>
		  <select id='id_linea' required style='width:350px;' />
            <option value=''>----------------</option>
            {% for l in listar_lineas %}
            <option value='{{l.id}}'>{{l.linea}}</option>
            {% endfor %}
        </select>
		</td>
	  </tr>
	  <tr>
		<td>
		  <button id="reporte_linea" class='btn btn-danger'>Generar Reporte</button>
		</td>
	  </tr>
	</table>
    {% endblock contenido%}
<!-- ************************************************************* -->