apps/categorias/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, url
from .views import ListarCategorias, RegistrarCategoria, ActualizarCategoria, EliminarCategoria

"""
    Nota: Para cada elemento 'url' de 'urlpatterns' se debe tener en cuenta que el segundo argumento se
    indica de acuerdo a lo declarado en el view, ya que si las vista son declaradas con clases la sintaxis
    es clase.as_view() y si las vistas son declaradas con funciones entonces la sintaxis cambia a
    'ruta.del.views.funcion'
"""

urlpatterns = [
    url(r'^listar_categorias/$', 'apps.categorias.views.ListarCategorias', name="listar_categorias",),
    url(r'^registrar_categoria/', 'apps.categorias.views.RegistrarCategoria', name="registrar_categoria",),
    url(r'^actualizar_categoria/(?P<pk>\d+)/$', 'apps.categorias.views.ActualizarCategoria', name="actualizar_categoria",),
    url(r'^eliminar_categoria/(?P<pk>\d+)/$', 'apps.categorias.views.EliminarCategoria', name="eliminar_categoria",),
    #url(r'^busqueda_ajax_centros/$','apps.registro.views.BuscarAjaxCentros', name='listar_centros',),
    #url(r'^busqueda_ajax2/$','apps.registro.views.BuscarAjaxPar', name='listar_municipios',),
    url(r'^data/', 'apps.categorias.views.load_data', name="datos_categorias",),  # URL de Importación para la data
]

bva_libros/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework.routers import DefaultRouter
import settings

#router = DefaultRouter()
#router.register(r'registro', FichaPersonalViewSet)
urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'fumtea.views.home', name='home'),
                       url(r'^iniciar/', include('apps.login.urls')),
                       url(r'^libros/', include('apps.libros.urls')),
                       # Url direccion a la URL login
                       url(r'^$', 'apps.libros.views.home', name='home'),  # Url direccion a la URL login
                       url(r'^admin/', include(admin.site.urls)),
                       #url(r'^/', include(router.urls)),
                       url(r'^categorias/', include('apps.categorias.urls')),
                       url(r'^autores/', include('apps.autores.urls')),
                       url(r'^editoriales/', include('apps.editoriales.urls')),
                       url(r'^ejes/', include('apps.ejes.urls')),
                       url(r'^sedes/', include('apps.sedes.urls')),
                       url(r'^usuarios/', include('apps.login.urls')),
                       url(r'^bitacora/', include('apps.bitacora.urls')),
                       url(r'^foto/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^reporte/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PDF}),
                       )

apps/categorias/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from apps.bitacora.models import Bitacora
from django.contrib.auth.models import User

# Create your models here.


class Categoria(models.Model):
    """
    Clase para el mantenimiento de categorías:
    Registrar, Modificar, Eliminar y Consultar

    :param CharField cod_categoria: campo donde se crea el código de la categoría.
    :param CharField categoria: campo donde se registra el nombre de la categoría.
    :param DateTimeField date_create: campo donde se registra la fecha de creación de la categoría.
    :param DateTimeField date_update: campo donde se registra la fecha de actualización de la categoría.
    :param CharField user: campo donde se registra el usuario que ha manipulado el módulo.
    """
    cod_categoria = models.CharField(verbose_name="Código de la categoría", unique=True, max_length=15)
    categoria = models.CharField(verbose_name="Categoria", max_length=200)
    #Auditoria
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    fecha_create = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    fecha_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True, blank=True)

    def __unicode__(self):
        # Método para retornar por defecto el valor de un campo especificado
        return self.cod_categoria

apps/categorias/forms.py
from django.forms import ModelForm
from django import forms
from apps.categorias.models import Categoria


class FormCategorias(ModelForm):
    class Meta:
        model = Categoria
        exclude = {'user', }

apps/categorias/views.py
# -*- encoding: utf-8 -*-
import datetime
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Bitacora
from .models import Categoria
from .forms import FormCategorias
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  # Paginacion
from django.contrib.auth.decorators import login_required  # Forma para impedir el acceso al sistema
from django.core import serializers
import os
import csv
from django.conf import settings


# Create your views here.
@login_required(login_url='/iniciar/login/')
def ListarCategorias(request):
    """
    Función para listar los cargos. Se usa 'context_object_name' para enviar los registros del
    modelo a la vista especificada.

    :param cargos: variable que contiene todos los objetos del modelo Categoria.
    :param paginator: variable que hace una lista del contenido de la variable cargos.
    :param page: variable que obtiene el número de página.
    """
    listar_categorias = Categoria.objects.all()
    #paginator = Paginator(cargos, 10)  # Show 5 contacts per page
    #page = request.GET.get('page')
    #try:
    #    listar_categorias = paginator.page(page)
    #except PageNotAnInteger:
    #    # If page is not an integer, deliver first page.
    #    listar_categorias = paginator.page(1)
    #except EmptyPage:
    #    # If page is out of range (e.g. 9999), deliver last page of results.
    #    listar_categorias = paginator.page(paginator.num_pages)
    ctx = {'listar_categorias': listar_categorias}  # ctx = Contexto
    return render_to_response('categorias/lista.html', ctx, context_instance=RequestContext(request))


@login_required(login_url='/iniciar/login/')
def RegistrarCategoria(request):  # Forma actual
    """
        Función para registrar una nueva categoria.

        :param num_categorias: variable donde se cuenta el número de objetos del modelo Categoria.
    """
    num_categorias = Categoria.objects.count()  # Número de cargos registrados
    # Conversión del número de cargos anteponiendo ceros a la izquierda hasta alcanzar el límite de 4 dígitos
    num_categorias = "CT"+str(num_categorias+1).zfill(4)
    #estados = Estado.objects.all()
    if request.method == 'POST':
        #print "DATOS: ", request
        from_rcategoria = FormCategorias(request.POST, request.FILES)
        if from_rcategoria.is_valid():
            nuevo_rcategoria = from_rcategoria.save(commit=False)
            nuevo_rcategoria.user = request.user.username
            nuevo_rcategoria.save()
            x = datetime.datetime.now()
            #print "Fecha y Hora: "+str(x)
            reg_bitacora = Bitacora(
                accion="Registro de nueva categoria ("+str(request.POST['cod_categoria'])+")...",
                usuario=request.user.username,
                fecha=x,)
            reg_bitacora.save()
            return HttpResponseRedirect('/categorias/listar_categorias')
    else:
        from_rcategoria = FormCategorias()
    ctx = {'from_rcategoria': from_rcategoria, 'num_categorias': num_categorias}  # ctx = Contexto (datos de los modelos)
    return render_to_response('categorias/nueva_categoria.html', ctx, context_instance=RequestContext(request))


@login_required(login_url='/iniciar/login/')
def ActualizarCategoria(request, pk):
    """
        Función para editar los datos de una categoria.

        :param obj_rcategoria: variable que obtiene el objeto (categoria) que coincida con el valor del parámetro pk
    """
    #estados = Estado.objects.all()
    obj_rcategoria = Categoria.objects.get(id=pk)
    if request.method == 'POST':
        form_rcategoria = FormCategorias(request.POST, request.FILES, instance=obj_rcategoria)
        if form_rcategoria.is_valid():
            edit_rcategoria = form_rcategoria.save(commit=False)
            edit_rcategoria.user = request.user.username
            edit_rcategoria.save()
            x = datetime.datetime.now()
            #print "Fecha y Hora: "+str(x)
            reg_bitacora = Bitacora(
                accion="Actualización de la categoría '"+str(request.POST['cod_categoria'])+"'...",
                usuario=request.user.username,
                fecha=x,)
            reg_bitacora.save()
            return HttpResponseRedirect('/categorias/listar_categorias')
    else:
        form_rcategoria = FormCategorias(instance=obj_rcategoria)
    ctx = {'form_rcategoria': form_rcategoria, 'obj_rcategoria': obj_rcategoria}  # ctx = Contexto
    return render_to_response('categorias/edit_categoria.html', ctx, context_instance=RequestContext(request))


@login_required(login_url='/iniciar/login/')
def EliminarCategoria(request, pk):
    """
        Función para eliminar una categoría. Se usa 'context_object_name' para enviar el registro del modelo
        a la vista especificada.

        :param obj_rcategoria: variable que obtiene el objeto (categoría) que coincida con el valor del parámetro pk
    """
    obj_rcategoria = Categoria.objects.get(id=pk)
    obj_rcategoria.delete()
    x = datetime.datetime.now()
    #print "Fecha y Hora: "+str(x)
    reg_bitacora = Bitacora(
        accion="Eliminación de la categoría '"+str(obj_rcategoria.cod_categoria)+"'...",
        usuario=request.user.username,
        fecha=x,)
    reg_bitacora.save()
    return HttpResponseRedirect('/categorias/listar_categorias')


#======================================================================================
# Importar data CSV de los cargos predefinidos
#======================================================================================
@login_required(login_url='/iniciar/login/')
def load_data(request):
    """
    Función para la carga de la data por defecto del módulo de categorías.

    :param DIR_URL: variable que almacena la ruta del proyecto.
    """

    os.path.dirname(os.path.abspath(__file__))

    DIR_URL = settings.BASE_DIR

    reader = csv.reader(open(DIR_URL+str("/apps/categorias/script/categorias.csv")))
    # Recorrido de los registros
    for row in reader:
        data = row[0].split(';')
        consulta_categoria = Categoria.objects.filter(cod_categoria=data[0])
        if consulta_categoria:
            print "Ya existe..."
        else:
            categoria = Categoria(
                cod_categoria=data[0],
                categoria=data[1],
                user_create_id=data[2],
                )
            categoria.save()

            x = datetime.datetime.now()
            reg_bitacora = Bitacora(
                accion="Registro de nueva categoría desde csv ("+str(data[0])+")...",
                usuario=request.user.username,
                fecha=x,)
            reg_bitacora.save()

    return HttpResponseRedirect('/categorias/listar_categorias')
#======================================================================================

templates/categorias/edit_categoria.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block title %}Actualizar Categoría{% endblock title%} <!--Bloque para definir el título-->



{% block contenido %} <!-- Apertura de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->
<script type="text/javascript">
$(document).ready(function(){
	$('#id_categoria').alpha({allow:" "}); //Valida solo valores tipo texto
	    
	// Validamos los campos del formulario
	$("#actualizar").click(function(e) {
	   e.preventDefault();  // Para evitar que se envíe por defecto
		    
	    if($('#id_categoria').val().trim() == ''){
		bootbox.alert("Rellene el campo de categoría", function () {
		$('#id_categoria').parent('div').addClass('has-error');
		});
		$('#id_categoria').focus();
	    }else{
		$('#form_categoria').submit();
		}
	});
	
	$('#volver').click(function(){
	    url = '/categorias/listar_categorias'
	    window.location = url
	})
	
});
</script>
<body>
    <form method="post" id="form_categoria">
	{% csrf_token %}
	<div class='panel panel-default' style='width:60%'>
		    <div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Actualizar Categoría</div>
		    <br>
	<table style="text-align:center;border-collapse: separate;border-spacing: 5px 15px;">
            <tr>
		<td><input id="id_cod_categoria" required name="cod_categoria" type="hidden" value='{{obj_rcategoria.cod_categoria}}'/>
		</td>
	    </tr>
	    <tr>
		<td>Categoria:</td>
		<td>
			<input id="id_categoria" required name="categoria" type="text" value='{{obj_rcategoria.categoria}}'/>
			<input type='hidden' id="id_user_create" name="user_create" value='{{obj_rcategoria.user_create.id}}'/>
			<input type='hidden' id="id_user_update" name="user_update" value='{{user.id}}'/>
		</td>
	    </tr>
	    <tr>
		<td colspan='2'>
			<input type="submit" id="actualizar" value="Actualizar"/>
			<input type="button" id="volver" value="Volver" class="btn btn-primary"/>
		</td>
	    </tr>
	</table>
</div>
    </form>
</body>
</html>
{% endblock contenido %} <!-- Cierre de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->

templates/categorias/lista.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->
    {% block title %}Lista de Categorías{% endblock title%}
    {% if form.non_field_errors %}
    <div class="panel">
      {{ form.non_field_errors }}
    </div>
  {% endif %}
  {% block contenido %}
    <script>
	    $(document).ready( function () {
	    $("#id_configuracion").attr('class','active');
            var TCargo = $('#lista_categorias').dataTable({
              "iDisplayLength": 5,
              "iDisplayStart": 0,
              "sPaginationType": "full_numbers",
              "aLengthMenu": [5, 10, 20, 30, 40, 50],
              "oLanguage": {"sUrl": "/static/js/es.txt"},
              "aoColumns": [
                  {"sClass": "registro center", "sWidth": "1%"},
                  {"sClass": "registro center", "sWidth": "8%"},
                  {"sWidth": "3%", "bSortable": false, "sClass": "center sorting_false", "bSearchable": false}
              ]
            });
        } );
	</script>
        {% load templatag_grupos %}
	<div class='panel panel-default' style='width:90%'>
	<div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Listado de Categorías</div>
    <br>
    <div style='width: 60em;'>
    <table class='table table-striped table-hover' id='lista_categorias'>
      <thead>
      <tr>
        <th colspan=3>
          {% ifusergroup administrador %}
          <a href='/categorias/data'>
            <button class='btn btn-default'>Importar Categorías</button>
          </a>
          {% endifusergroup %}
           <a href="/categorias/registrar_categoria" title='Nuevo'>  
            <button class='btn btn-default'>Registrar Categoría</button>
          </a>
        </th>
      </tr>
      <tr style='background-color: #E86639; color:white;'>
        <th style='text-align: left;'><b>Código</b></th>
        <th style='text-align: left;'><b>Categoría</b></th>
        <th style='text-align: right;'>Acción</th>
      </tr>
      </thead>
      <tbody>
      {% for ct in listar_categorias %}
      <tr>
        <td style="text-align: left !important;">{{ ct.cod_categoria }}</td>
        <td style="text-align: left !important;">{{ ct.categoria }}</td>
        <td style="text-align: right !important;">
          <a href='{% url "actualizar_categoria" ct.id %}'>
            <img src='/static/image/editar.png' title='Editar' style="width:30px;height:30px;">
          </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <a onclick="eliminar_data('{{ct.id}}', '/categorias/eliminar_categoria/')">
            <img src='/static/image/eliminar.png' title='Eliminar'>
          </a>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
    </div>
    <br>
    </div>
    {% endblock contenido%}
<!-- ************************************************************* -->

templates/categorias/nueva_categoria.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block title %}Registrar Categoria{% endblock title%} <!--Bloque para definir el título-->


{% block contenido %} <!-- Apertura de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2-bootstrap.css">
	
<script src="{{STATIC_URL}}js/select2/select2.js"></script>
<script src="{{STATIC_URL}}js/select2/select2_locale_es.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('#id_categoria').alpha({allow:" -"}); //Valida solo valores tipo texto
	    
	// Validamos los campos del formulario
	$("#registrar").click(function(e) {
	   e.preventDefault();  // Para evitar que se envíe por defecto
		    
	    if($('#id_categoria').val().trim() == ''){
		bootbox.alert("Rellene el campo de categoría", function () {
		$('#id_categoria').parent('div').addClass('has-error');
		});
		$('#id_categoria').focus();
	    }else{
		$('#form_categoria').submit();
		}
	});
	
	$('#volver').click(function(){
	    url = '/categorias/listar_categorias'
	    window.location = url
	})
	
});
</script>
<body>
    <form method="post" id="form_categoria">
	{% csrf_token %}
	<div class='panel panel-default' style='width:60%'>
		    <div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Registrar Categoría</div>
		    <br>
	<table style="text-align:center;border-collapse: separate;border-spacing: 5px 15px;">
            <tr>
		<td><input id="id_cod_categoria" required name="cod_categoria" type="hidden" value='{{num_categorias}}'/>
		</td>
	    </tr>
	    <tr>
		<td>Categoria:</td>
		<td>
			<input id="id_categoria" required name="categoria" type="text" />
			<input type='hidden' id="id_user_update" name="user_create" value='{{user.id}}'/>
		</td>
	    </tr>
	    <tr>
		<td colspan='2'>
			<input type="submit" id="registrar" value="Registrar"/>
			<input type="button" id="volver" value="Volver" class="btn btn-primary"/>
		</td>
	    </tr>
	</table>
</div>
    </form>
</body>
</html>
{% endblock contenido %} <!-- Cierre de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->