apps/topologia/estados/urls.py
from django.conf.urls import url
from .views import RegistrarEstado ,ActualizarEstado, EliminarEstado,ListarEstado, base_view, load_data

urlpatterns = [
    url(r'^registrar_estado/$','apps.topologia.estados.views.RegistrarEstado'),
    url(r'^actualizar_estado/(?P<pk>\d+)/$','apps.topologia.estados.views.ActualizarEstado', name='actualizar_estado'),
    url(r'^eliminar_estado/(?P<pk>\d+)/$', 'apps.topologia.estados.views.EliminarEstado'),
    #url(r'^registrar_estado/', RegistrarEstado.as_view(), name="registrar_estados",),
    #url(r'^actualizar_estado/(?P<pk>\d+)/$', ActualizarEstado.as_view(), name='actualizar_estado',),
    #url(r'^eliminar_estado/(?P<pk>\d+)/$', EliminarEstado.as_view(), name='eliminar_estado',),
    url(r'^$', 'apps.topologia.estados.views.base_view', name="home",), # URL de Exportacion para la data
    url(r'^lista_estado/$','apps.topologia.estados.views.ListarEstado',name='listar_estados',),
    url(r'^data/', 'apps.topologia.estados.views.load_data', name="datos_estados",), # URL de Exportacion para la data
]

apps/topologia/municipios/urls.py
from django.conf.urls import url
from .views import RegistrarMunicipio, ActualizarMunicipio, EliminarMunicipio, ListarMunicipio, load_data  # Importamos las Vistas


urlpatterns = [
    url(r'^registrar_municipio/', 'apps.topologia.municipios.views.RegistrarMunicipio', name="registrar_municipio",),
    url(r'^actualizar_municipio/(?P<pk>\d+)/$', 'apps.topologia.municipios.views.ActualizarMunicipio', name='actualizar_municipio',),
    url(r'^eliminar_municipio/(?P<pk>\d+)/$', 'apps.topologia.municipios.views.EliminarMunicipio', name='eliminar_municipio',),
    url(r'^listar_municipios/$', 'apps.topologia.municipios.views.ListarMunicipio', name='listar_municipio',),
    url(r'^data/', 'apps.topologia.municipios.views.load_data', name="datos_municipio",),  # URL de Exportacion para la data
]

apps/topologia/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.routers import DefaultRouter
from apps.topologia.estados.viewsets import EstadoViewSet
from apps.topologia.municipios.viewsets import MunicipioViewSet
from apps.topologia.parroquias.viewsets import ParroquiaViewset
from apps.linea.viewsets import LineaViewSet
#from apps.centro_votacion.viewsets import CentroVotacionViewSet
#from apps.registro.viewsets import RegistroViewSet


router = DefaultRouter()
router.register(r'estados', EstadoViewSet)
router.register(r'municipios', MunicipioViewSet)
router.register(r'parroquias', ParroquiaViewset)
router.register(r'lineas', LineaViewSet)
urlpatterns = patterns('',
                       url(r'^', include(router.urls))
                       )

bva_libros/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework.routers import DefaultRouter
import settings

#router = DefaultRouter()
#router.register(r'registro', FichaPersonalViewSet)
urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'fumtea.views.home', name='home'),
                       url(r'^iniciar/', include('apps.login.urls')),
                       url(r'^libros/', include('apps.libros.urls')),
                       # Url direccion a la URL login
                       url(r'^$', 'apps.libros.views.home', name='home'),  # Url direccion a la URL login
                       url(r'^admin/', include(admin.site.urls)),
                       #url(r'^/', include(router.urls)),
                       url(r'^categorias/', include('apps.categorias.urls')),
                       url(r'^autores/', include('apps.autores.urls')),
                       url(r'^editoriales/', include('apps.editoriales.urls')),
                       url(r'^ejes/', include('apps.ejes.urls')),
                       url(r'^sedes/', include('apps.sedes.urls')),
                       url(r'^usuarios/', include('apps.login.urls')),
                       url(r'^bitacora/', include('apps.bitacora.urls')),
                       url(r'^foto/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^reporte/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PDF}),
                       )

apps/topologia/estados/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from apps.bitacora.models import Bitacora

# Esta es mi CLASE.


class Estado(models.Model):
    """
	Esta es la Clase que define todo lo referente a los estados
        Registrar Modificar Eliminar y Consultar
	
	:param CharField cod_estado: campo donde se registra el código del estado.
	:param CharField estado: campo donde se registra el nombre del estado.
	:param DateTimeField date_create: campo donde se registra la fecha y hora de creación del estado.
	:param DateTimeField date_update: campo donde se registra la fecha y hora de actualización del estado.
	:param CharField user: campo donde se registra el usuario que ha manipulado el módulo.
    """
    cod_estado = models.IntegerField(unique=True)
    estado = models.CharField(max_length=50)
    date_create = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    date_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    user = models.CharField(max_length=15, null=True, blank=True)
    
    

    def __unicode__(self):
        return self.estado

apps/topologia/municipios/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from ..estados.models import Estado
from apps.circuitos.models import Circuitos
from apps.bitacora.models import Bitacora


class Municipio(models.Model):
    """
	Esta es la Clase que define todo lo referente a los estados
        Registrar Modificar Eliminar y Consultar
	
	:param CharField municipio: campo donde se registra el nombre del municipio.
	:param IntegerField cod_municipio: campo donde se registra el código del estado.
	:param ForeignKey estado: campo de clave foránea donde se regitra el código del estado asociado al municipio.
	:param ForeignKey circuito: campo de clave foránea donde se regitra el código del circuito asociado al municipio.
	:param DateTimeField date_create: campo donde se registra la fecha y hora de creación del municipio.
	:param DateTimeField date_update: campo donde se registra la fecha y hora de actualización del municipio.
	:param CharField user: campo donde se registra el usuario que ha manipulado el módulo.
    """
    municipio = models.CharField(verbose_name="Municipio", max_length=50)
    cod_municipio = models.IntegerField(null=True)
    estado = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL, related_name='estado_municipio', null=True) # Clave unica que hace referencia a estado a traves de cod_estado con clave unica (unique)
    circuito = models.ForeignKey(Circuitos, to_field='codigo', on_delete=models.SET_NULL, related_name='circuito_municipio', null=True)
    date_create = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    date_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    user = models.CharField(max_length=15, null=True)

    def __unicode__(self):
        return self.municipio

apps/topologia/parroquias/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from smart_selects.db_fields import ChainedForeignKey
from ..estados.models import Estado
from ..municipios.models import Municipio
from apps.bitacora.models import Bitacora


class Parroquia(models.Model):
	"""
	Esta es la Clase que define todo lo referente a los parroquias
	Registrar Modificar Eliminar y Consultar
	
	:param CharField parroquia: campo donde se registra el nombre de la parroquia.
	:param ForeignKey estado: campo donde se registra el código del estado.
	:param IntegerField cod_parroquia: campo donde se registra el código de la parroquia.
	:param IntegerField municipio: campo donde se registra el código del municipio.
	:param DateTimeField date_create: campo donde se registra la fecha y hora de creación del parroquia.
	:param DateTimeField date_update: campo donde se registra la fecha y hora de actualización del parroquia.
	:param CharField user: campo donde se registra el usuario que ha manipulado el módulo.
	"""
	parroquia = models.CharField(max_length=50)
	estado = models.ForeignKey(Estado, to_field='cod_estado', on_delete=models.SET_NULL, related_name='estado_parroquia', null=True)
	cod_parroquia = models.IntegerField(null=True)
	municipio = models.IntegerField(null=True)
	date_create = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
	date_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
	user = models.CharField(max_length=15, null=True)

	def __unicode__(self):
		return self.parroquia

	def __str__(self):
		return self.parroquia

apps/topologia/estados/forms.py
from django.forms import ModelForm
from django import forms
from apps.topologia.estados.models import Estado

class FormEstado(ModelForm):
    class Meta:
	model = Estado
	exclude = {'user',}

apps/topologia/municipios/forms.py
from django.forms import ModelForm
from django import forms
from apps.topologia.municipios.models import Municipio

class FormMunicipio(ModelForm):
    class Meta:
	model = Municipio
	exclude = {'user',}

apps/topologia/parroquias/forms.py
from django.forms import ModelForm
from django import forms
from apps.topologia.parroquias.models import Parroquia

class FormParroquia(ModelForm):
    class Meta:
        model = Parroquia
        exclude = {'user',}

apps/topologia/estados/views.py
# -*- encoding: utf-8 -*-
import datetime
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from .models import Bitacora
from .models import Estado
from .forms import FormEstado
from django.views.generic.dates import ArchiveIndexView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render_to_response
from django.contrib import messages # Metodo para la validacion de los campos
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger # Paginacion
from django.contrib.auth.decorators import login_required # Forma para impedir el acceso al sistema
import os
import csv
#=====================================================================================
#                            # Clase RegistrarEstado
#=====================================================================================
@login_required(login_url='/iniciar/login/')
def RegistrarEstado(request):
    """
        Función para registrar un estado nuevo.

        :param x: variable que contiene la fecha y hora actual.
        :param reg_bitacora: variable que contiene la asignación de un nuevo registro al modelo Bitacora.
    """
    if request.method=='POST':
        form_regestado = FormEstado(request.POST, request.FILES)
        if form_regestado.is_valid():
            nuevo_regestado = form_regestado.save(commit=False)
            nuevo_regestado.user = request.user.username
            nuevo_regestado.save()
            x = datetime.datetime.now()
            reg_bitacora = Bitacora(
            	accion="Registro de nuevo estado ("+str(request.POST['cod_estado'])+")...",
		usuario=request.user.username,
		fecha=x,)
            reg_bitacora.save()
	    return HttpResponseRedirect('/estado/lista_estado')
    else:
         form_regestado = FormEstado()
    ctx = {'form_regestado':form_regestado} # ctx = Contexto
    return render_to_response('topologia/estado/registrar_estado.html',ctx, context_instance=RequestContext(request))
    

#=====================================================================================
                            # Clase ActualizarEstado
#=====================================================================================
@login_required(login_url='/iniciar/login/')
def ActualizarEstado(request,pk):
    """
        Función para actualizar los datos de un estado.

        :param obj_regestado: variable que contiene el objeto del modelo Estado que coincide con un id dado.
        :param x: variable que contiene la fecha y hora actual.
        :param reg_bitacora: variable que contiene la asignación de un nuevo registro al modelo Bitacora.
    """
    obj_regestado = Estado.objects.get(id=pk)
    if request.method=='POST':
        form_regestado = FormEstado(request.POST, request.FILES, instance=obj_regestado)
        if form_regestado.is_valid():
            edit_regestado = form_regestado.save(commit=False)
            edit_regestado.user = request.user.username
            edit_regestado.save()
	    x = datetime.datetime.now()
            reg_bitacora = Bitacora(
            	accion="Actualización del estado '"+str(request.POST['cod_estado'])+"'...",
		usuario=request.user.username,
		fecha=x,)
            reg_bitacora.save()
            return HttpResponseRedirect('/estado/lista_estado')
    else:
        form_regestado = FormEstado(instance=obj_regestado)
    ctx = {'form_regestado':form_regestado,'obj_regestado':obj_regestado} # ctx = Contexto
    return render_to_response('topologia/estado/actualizar_estado.html',ctx, context_instance=RequestContext(request))

#=====================================================================================
                            # Clase EliminarEstado
#=====================================================================================
def EliminarEstado(request,pk):
    """
        Función para eliminar un estado.

        :param obj_regestado: variable que contiene el objeto del modelo Estado que coincide con un id dado.
        :param x: variable que contiene la fecha y hora actual.
        :param reg_bitacora: variable que contiene la asignación de un nuevo registro al modelo Bitacora.
    """
    obj_regestado = Estado.objects.get(id=pk)
    obj_regestado.delete()
    x = datetime.datetime.now()
    reg_bitacora = Bitacora(
    	accion="Eliminación del estado '"+str(obj_regestado.cod_estado)+"'...",
	usuario=request.user.username,
	fecha=x,)
    reg_bitacora.save()
    return HttpResponseRedirect('/estado/lista_estado')
#======================================================================================
# Metodo para listar Registros y Paginacion
#======================================================================================
@login_required(login_url='/iniciar/login/')
def ListarEstado(request):
    """
        Función para listar los estados.

        :param lista_estados: variable que contiene todos los objetos del modelo Estado.
    """
    lista_estados    = Estado.objects.all()
    ctx          = {'lista_estados':lista_estados,} # ctx = Contexto
    return render_to_response('topologia/estado/lista_estado.html',ctx, context_instance=RequestContext(request))

#======================================================================================
                    # Metodo para renderizar a /
#=====================================================================================

def base_view(request):
    
    return render_to_response('base/base.html',locals(), context_instance=RequestContext(request))
#======================================================================================
# Url Importar data CSV
#======================================================================================
@login_required(login_url='/iniciar/login/')
def load_data(request):
    """
    Función para la carga de la data por defecto del módulo de estados.

    :param DIR_URL: variable que almacena la ruta del proyecto.
    :param x: variable que contiene la fecha y hora actual.
    :param reg_bitacora: variable que contiene la asignación de un nuevo registro al modelo Bitacora.
    """

    os.path.dirname(os.path.abspath(__file__))

    DIR_URL = os.getcwd()

    reader = csv.reader(open(DIR_URL+str("/apps/topologia/estados/script/estados.csv")))
    
    # Recorrido de los registros
    for row in reader:
        data = row[0].split(';')
        estado = Estado.objects.filter(cod_estado=data[0])
        if estado:
            print "Ya existe"
            return HttpResponseRedirect('/estado/lista_estado')
        else:
            centro = Estado(
                cod_estado = data[0],
                estado = data[1],
                )
            centro.save()
            x = datetime.datetime.now()
            reg_bitacora = Bitacora(
            	accion="Registro de nuevo estado desde csv ("+str(data[0])+")...",
		usuario=request.user.username,
		fecha=x,)
            reg_bitacora.save()

    return HttpResponseRedirect('/estado/lista_estado')
#======================================================================================

def custom_404(request):
    return render_to_response('404.html', RequestContext(request))

templates/topologia/parroquia/actualizar_parroquias.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Actualizar Parroquias{% endblock %}
    
    {% block contenido %}
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2-bootstrap.css">
	
    <script src="{{STATIC_URL}}js/select2/select2.js"></script>
    <script src="{{STATIC_URL}}js/select2/select2_locale_es.js"></script>
    <script>
		$(document).ready(function() {
			$("select").select2();
			$("#id_configuracion").attr('class','active');
			$('#id_cod_parroquia').numeric({allow: ""});
			$('#id_parroquia').alpha({allow: " "});
		});
    </script>
	<form method="post">
	    {% csrf_token %}
	    <div class='panel panel-default' style='width:60%'>
		    <div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Actualizar Parrroquia</div>
		    <br>
	    <table style="text-align:center;border-collapse: separate;border-spacing: 5px 15px;">
	    	<tr>
		    <td>Código</td>
		    <td><input id="id_cod_parroquia" required=True name="cod_parroquia" type="text" value='{{obj_reg_parr.cod_parroquia}}' required=True/></td>
	    	</tr>
	    	<tr>
		    <td>Estado</td>
		    <td>
			<select id="id_cod_estado" name="estado" required=True>
			    <option value="">-----------------------------</option>
			    {% for e in list_e %}
				{% if e.cod_estado == obj_reg_parr.estado_id%}
				    <option value='{{e.cod_estado}}' selected='selected'>{{ e.estado }}</option>
				{% endif %}
				{% if not e.cod_estado == obj_reg_parr.estado_id %}
				    <option value='{{e.cod_estado}}'>{{ e.estado }}</option>
				{% endif %}
			    {% endfor %}
			</select>
		    </td>
	    	</tr>
	    	<tr>
		    <td>Municipio</td>
		    <td>
			<select id="id_cod_municipio" name="municipio" required=True>
			    <option value="">-----------------------------</option>
			    {% for est in list_e%}
				    {% for m in list_m %}
						{% if est.cod_estado == obj_reg_parr.estado_id and m.cod_municipio == obj_reg_parr.municipio%}
						<option value='{{m.cod_municipio}}' selected='selected'>{{m.municipio}}</option>
					    {% endif %}
					    {% if not m.cod_municipio == obj_reg_parr.municipio %}
						<option value='{{m.cod_municipio}}'>{{m.municipio}}</option>
					    {% endif %}
				    {% endfor %}
			    {%endfor%}
			</select>
		    </td>
		    </tr>
		    <tr>
			<td>Parroquia</td>
			<td><input id="id_parroquia" maxlength="50" name="parroquia" type="text" value='{{obj_reg_parr.parroquia}}' required=True/></td>
		    </tr>
	    	<tr>
	    	    <td colspan='3' style='text-align:right;'>
			<input type="submit" value="Actualizar"/>
		    </td>	
	    	</tr>
	    </table>
	</div>
	</form>
    {% endblock contenido%}

templates/topologia/parroquia/eliminar_parroquias.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Eliminar Parroquia{% endblock %}
    
    {% block contenido %}
	<form method="post">{% csrf_token %}
		¿ Esta seguro que desea eliminar el registro "{{ object }}"?
		<input type="submit" value="Eliminar" />
	</form>
	{% endblock contenido%}

templates/topologia/parroquia/lista_parroquia.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->
	{% block title %}Lista de Parroquias{% endblock title%}
	{% if form.non_field_errors %}
	<div class="panel">
	  {{ form.non_field_errors }}
	</div>
	{% endif %}

	{% block contenido %}
	<script>
	  $(document).ready( function () {
	      $("#id_configuracion").attr('class','active');
	      var TPartidos = $('#lista_parroquias').dataTable({
              "iDisplayLength": 5,
              "iDisplayStart": 0,
              "sPaginationType": "full_numbers",
              "aLengthMenu": [5, 10, 20, 30, 40, 50],
              "oLanguage": {"sUrl": "/static/js/es.txt"},
              "aoColumns": [
                  {"sClass": "registro center", "sWidth": "8%"},
                  {"sClass": "registro center", "sWidth": "8%"},
                  {"sClass": "registro center", "sWidth": "8%"},
                  {"sWidth": "3%", "bSortable": false, "sClass": "center sorting_false", "bSearchable": false}
              ]
          });
          
	  } );
	</script>
	<!-- ************************************************************* -->
	<div class='panel panel-default' style='width: 90%;'>
    <div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Listado de Parroquias</div>
    <br>
	  <div style='width: 60em;'>
	    <table class='table table-striped table-hover' id='lista_parroquias'>
		<thead>
	    <tr>
		  <th colspan=5>
			<a href='/parroquia/data'>
			  <button class='btn btn-default'>Importar Parroquias</button>
			</a>
			<a href="/parroquia/registrar_parroquia" title='Nuevo'>  
		    	<button class='btn btn-default'>Registrar Parroquia</button>
		  	</a>
		  </th>
		</tr>
	    <tr style='background-color: #E86639; color:white;'>
		  <th style='text-align: center;'>Estado</th>
		  <th style='text-align: center;'>Municipio</th>
		  <th style='text-align: center;'>Parroquia</th>
		  <th style='text-align: center;'>Acción</th>
	    </tr>
		</thead>
		<tbody>
	    {% for p in list_parroquia %}
	    <tr class="{% cycle 'impar' 'par' %}">
		  <td>
			  {% for e in list_estado %}
				  {% if e.cod_estado == p.estado_id %}
					  {{ e.estado }}
				  {% endif %}
			  {% endfor%}
		  </td>
		  <td>
		  	{% for m in list_municipio %}
		  		{% if m.cod_municipio == p.municipio and m.estado_id == p.estado_id %}
		  			{{m.municipio}}
		  		{% endif %}
		  	{% endfor %}
		  </td>
		  <td>{{ p.parroquia }}</td>
		  <td>
			<a href='{% url "actualizar_parroquia" p.id %}'>
			  <img src='../../static/admin/img/icon_changelink.gif' title='Editar'>
			</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<a onclick="eliminar_data('{{p.id}}','/parroquia/eliminar_parroquia/')">
			  <img src='../../static/admin/img/icon_deletelink.gif' title='Eliminar'>
			</a>
		  </td>
	    </tr>
	  {% endfor %}
	    </tbody>
	    </table>
	  </div>
	  <br>
	  </div>
	{% endblock contenido%}
	<!-- ************************************************************* -->

templates/topologia/parroquia/registrar_parroquias.html
{% extends "base/base.html" %} <!-- Bloque, Plantilla base -->
    {% block title %}Registrar Parroquias{% endblock %}
    
    {% block contenido %}
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2-bootstrap.css">
	
    <script src="{{STATIC_URL}}js/select2/select2.js"></script>
    <script src="{{STATIC_URL}}js/select2/select2_locale_es.js"></script>
    <script>
		$(document).ready(function() {
			$("select").select2();
			$("#id_configuracion").attr('class','active');
			$('#id_cod_parroquia').numeric({allow: ""});
			$('#id_parroquia').alpha({allow: " "});
		});
    </script>
	<form method="post">
	    {% csrf_token %}
	    <div class='panel panel-default' style='width:60%'>
		    <div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Registrar Parrroquia</div>
		    <br>
	    <table style="text-align:center;border-collapse: separate;border-spacing: 5px 15px;">
	    	<tr>
		    <td>Código</td>
		    <td><input id="id_cod_parroquia" required=True name="cod_parroquia" type="text" required=True /></td>
	    	</tr>
	    	<tr>
		    <td>Estado</td>
		    <td>
			<select id="id_cod_estado" name="estado" required=True>
			    <option value="">-----------------------------</option>
			    {% for e in list_e %}
			    <option value='{{e.cod_estado}}'>{{ e.estado }}</option>
			    {% endfor %}
			</select>
		    </td>
	    	</tr>
	    	<tr>
		    <td>Municipio</td>
		    <td>
			<select id="id_cod_municipio" name="municipio" required=True>
			    <option value="">-----------------------------</option>
			</select>
		    </td>
		    </tr>
		    <tr>
			<td>Parroquia</td>
			<td><input id="id_parroquia" maxlength="50" name="parroquia" type="text" required=True/></td>
		    </tr>
	    	<tr>
	    	    <td colspan='3' style='text-align:right;'>
			<input type="submit" value="Registrar"/>
		    </td>	
	    	</tr>
	    </table>
	</div>
	</form>
    {% endblock contenido%}