apps/autores/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, url
from .views import ListarAutores, RegistrarAutor, ActualizarAutor, EliminarAutor

"""
    Nota: Para cada elemento 'url' de 'urlpatterns' se debe tener en cuenta que el segundo argumento se
    indica de acuerdo a lo declarado en el view, ya que si las vista son declaradas con clases la sintaxis
    es clase.as_view() y si las vistas son declaradas con funciones entonces la sintaxis cambia a
    'ruta.del.views.funcion'
"""

urlpatterns = [
    url(r'^listar_autores/$', 'apps.autores.views.ListarAutores', name="listar_autores",),
    url(r'^registrar_autor/', 'apps.autores.views.RegistrarAutor', name="registrar_autor",),
    url(r'^actualizar_autor/(?P<pk>\d+)/$', 'apps.autores.views.ActualizarAutor', name="actualizar_autor",),
    url(r'^eliminar_autor/(?P<pk>\d+)/$', 'apps.autores.views.EliminarAutor', name="eliminar_autor",),
    #url(r'^busqueda_ajax_centros/$','apps.registro.views.BuscarAjaxCentros', name='listar_centros',),
    #url(r'^busqueda_ajax2/$','apps.registro.views.BuscarAjaxPar', name='listar_municipios',),
    url(r'^data/', 'apps.autores.views.load_data', name="datos_autores",),  # URL de Importación para la data
]

bva_libros/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework.routers import DefaultRouter
import settings

#router = DefaultRouter()
#router.register(r'registro', FichaPersonalViewSet)
urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'fumtea.views.home', name='home'),
                       url(r'^iniciar/', include('apps.login.urls')),
                       url(r'^libros/', include('apps.libros.urls')),
                       # Url direccion a la URL login
                       url(r'^$', 'apps.libros.views.home', name='home'),  # Url direccion a la URL login
                       url(r'^admin/', include(admin.site.urls)),
                       #url(r'^/', include(router.urls)),
                       url(r'^categorias/', include('apps.categorias.urls')),
                       url(r'^autores/', include('apps.autores.urls')),
                       url(r'^editoriales/', include('apps.editoriales.urls')),
                       url(r'^ejes/', include('apps.ejes.urls')),
                       url(r'^sedes/', include('apps.sedes.urls')),
                       url(r'^usuarios/', include('apps.login.urls')),
                       url(r'^bitacora/', include('apps.bitacora.urls')),
                       url(r'^foto/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^reporte/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_PDF}),
                       )

apps/autores/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from apps.bitacora.models import Bitacora
from django.contrib.auth.models import User

# Create your models here. (Crea tus modelos aquí)


class Autor(models.Model):
    """
    Clase para el mantenimiento de categorías:
    Registrar, Modificar, Eliminar y Consultar

    :param CharField cod_categoria: campo donde se crea el código de la categoría.
    :param CharField categoria: campo donde se registra el nombre de la categoría.
    :param DateTimeField date_create: campo donde se registra la fecha de creación de la categoría.
    :param DateTimeField date_update: campo donde se registra la fecha de actualización de la categoría.
    :param CharField user: campo donde se registra el usuario que ha manipulado el módulo.
    """
    cod_autor = models.CharField(verbose_name="Código del autor", unique=True, max_length=15)
    autor = models.CharField(verbose_name="Autor", max_length=200)
    #Auditoría
    user_create = models.ForeignKey(User, null=True, blank=True, related_name='+')
    user_update = models.ForeignKey(User, null=True, blank=True, related_name='+')
    fecha_create = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    fecha_update = models.DateTimeField(auto_now_add=False, auto_now=True, null=True, blank=True)

    def __unicode__(self):
        # Método para retornar por defecto el valor de un campo especificado
        return self.cod_autor

apps/autores/forms.py
from django.forms import ModelForm
from django import forms
from apps.autores.models import Autor


class FormAutores(ModelForm):
    class Meta:
        model = Autor
        exclude = {'user', }

apps/autores/views.py
# -*- encoding: utf-8 -*-
import datetime
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Bitacora
from .models import Autor
from .forms import FormAutores
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  # Paginación
from django.contrib.auth.decorators import login_required  # Forma para impedir el acceso al sistema
from django.core import serializers
import os
import csv
from django.conf import settings


# Create your views here. (Crea tus vistas aquí)
@login_required(login_url='/iniciar/login/')
def ListarAutores(request):
    """
    Función para listar los autores.

    :param listar_autores: variable que contiene todos los objetos del modelo Autor.
    """
    listar_autores = Autor.objects.all()
    ctx = {'listar_autores': listar_autores}  # ctx = Contexto
    return render_to_response('autores/lista.html', ctx, context_instance=RequestContext(request))


@login_required(login_url='/iniciar/login/')
def RegistrarAutor(request):  # Forma actual
    """
        Función para registrar uno nuevo autor.

        :param num_autores: variable donde se cuenta el número de objetos del modelo Autor.
    """
    num_autores = Autor.objects.count()  # Número de cargos registrados
    # Conversión del número de cargos anteponiendo ceros a la izquierda hasta alcanzar el límite de 4 dígitos
    num_autores = "A"+str(num_autores+1).zfill(4)
    if request.method == 'POST':
        #print "DATOS: ", request
        from_rautor = FormAutores(request.POST, request.FILES)
        if from_rautor.is_valid():
            nuevo_rautor = from_rautor.save(commit=False)
            nuevo_rautor.user = request.user.username
            nuevo_rautor.save()
            x = datetime.datetime.now()
            #print "Fecha y Hora: "+str(x)
            reg_bitacora = Bitacora(
                accion="Registro de nuevo autor ("+str(request.POST['cod_autor'])+")...",
                usuario=request.user.username,
                fecha=x,)
            reg_bitacora.save()
            return HttpResponseRedirect('/autores/listar_autores')
    else:
        from_rautor = FormAutores()
    ctx = {'from_rautor': from_rautor, 'num_autores': num_autores}  # ctx = Contexto (datos de los modelos)
    return render_to_response('autores/nuevo_autor.html', ctx, context_instance=RequestContext(request))


@login_required(login_url='/iniciar/login/')
def ActualizarAutor(request, pk):
    """
        Función para editar los datos de un autor.

        :param obj_rautor: variable que obtiene el objeto (autor) que coincida con el valor del parámetro pk
    """
    #estados = Estado.objects.all()
    obj_rautor = Autor.objects.get(id=pk)
    if request.method == 'POST':
        form_rautor = FormAutores(request.POST, request.FILES, instance=obj_rautor)
        if form_rautor.is_valid():
            edit_rautor = form_rautor.save(commit=False)
            edit_rautor.user = request.user.username
            edit_rautor.save()
            x = datetime.datetime.now()
            #print "Fecha y Hora: "+str(x)
            reg_bitacora = Bitacora(
                accion="Actualización del autor '"+str(request.POST['cod_autor'])+"'...",
                usuario=request.user.username,
                fecha=x,)
            reg_bitacora.save()
            return HttpResponseRedirect('/autores/listar_autores')
    else:
        form_rautor = FormAutores(instance=obj_rautor)
    ctx = {'form_rAutor': form_rautor, 'obj_rautor': obj_rautor}  # ctx = Contexto
    return render_to_response('autores/edit_autor.html', ctx, context_instance=RequestContext(request))


@login_required(login_url='/iniciar/login/')
def EliminarAutor(request, pk):
    """
        Función para eliminar una categoría. Se usa 'context_object_name' para enviar el registro del modelo
        a la vista especificada.

        :param obj_rautor: variable que obtiene el objeto (categoría) que coincida con el valor del parámetro pk
    """
    obj_rautor = Autor.objects.get(id=pk)
    obj_rautor.delete()
    x = datetime.datetime.now()
    #print "Fecha y Hora: "+str(x)
    reg_bitacora = Bitacora(
        accion="Eliminación del autor '"+str(obj_rautor.cod_autor)+"'...",
        usuario=request.user.username,
        fecha=x,)
    reg_bitacora.save()
    return HttpResponseRedirect('/autores/listar_autores')


#======================================================================================
# Importar data CSV de los cargos predefinidos
#======================================================================================
@login_required(login_url='/iniciar/login/')
def load_data(request):
    """
    Función para la carga de la data por defecto del módulo de autores.

    :param DIR_URL: variable que almacena la ruta del proyecto.
    """

    os.path.dirname(os.path.abspath(__file__))

    DIR_URL = settings.BASE_DIR

    reader = csv.reader(open(DIR_URL+str("/apps/autores/script/autores.csv")))
    # Recorrido de los registros
    for row in reader:
        data = row[0].split(';')
        consulta_autor = Autor.objects.filter(cod_autor=data[0])
        if consulta_autor:
            print "Ya existe..."
        else:
            autor = Autor(
                cod_autor=data[0],
                autor=data[1],
                user_create_id=data[2],
                )
            autor.save()

            x = datetime.datetime.now()
            reg_bitacora = Bitacora(
                accion="Registro de nuevo autor desde csv ("+str(data[0])+")...",
                usuario=request.user.username,
                fecha=x,)
            reg_bitacora.save()

    return HttpResponseRedirect('/autores/listar_autores')
#======================================================================================

templates/autores/edit_autor.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block title %}Actualizar autor{% endblock title%} <!--Bloque para definir el título-->



{% block contenido %} <!-- Apertura de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->
<script type="text/javascript">
$(document).ready(function(){
	$('#id_autor').alpha({allow:" "}); //Valida solo valores tipo texto
	    
	// Validamos los campos del formulario
	$("#actualizar").click(function(e) {
	   e.preventDefault();  // Para evitar que se envíe por defecto
		    
	    if($('#id_autor').val().trim() == ''){
		bootbox.alert("Rellene el campo de autor", function () {
		$('#id_autor').parent('div').addClass('has-error');
		});
		$('#id_autor').focus();
	    }else{
		$('#form_autor').submit();
		}
	});
	
	$('#volver').click(function(){
	    url = '/autores/listar_autores'
	    window.location = url
	})
	
});
</script>
<body>
    <form method="post" id="form_autor">
	{% csrf_token %}
	<div class='panel panel-default' style='width:60%'>
		    <div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Actualizar Autor</div>
		    <br>
	<table style="text-align:center;border-collapse: separate;border-spacing: 5px 15px;">
            <tr>
		<td><input id="id_cod_autor" required name="cod_autor" type="hidden" value='{{obj_rautor.cod_autor}}'/>
		</td>
	    </tr>
	    <tr>
		<td>Categoria:</td>
		<td>
			<input id="id_autor" required name="autor" type="text" value='{{obj_rautor.autor}}'/>
			<input type='hidden' id="id_user_create" name="user_create" value='{{obj_rautor.user_create.id}}'/>
			<input type='hidden' id="id_user_update" name="user_update" value='{{user.id}}'/>
		</td>
	    </tr>
	    <tr>
		<td colspan='2'>
			<input type="submit" id="actualizar" value="Actualizar"/>
			<input type="button" id="volver" value="Volver" class="btn btn-primary"/>
		</td>
	    </tr>
	</table>
</div>
    </form>
</body>
</html>
{% endblock contenido %} <!-- Cierre de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->

templates/autores/lista.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->
    {% block title %}Lista de Categorías{% endblock title%}
    {% if form.non_field_errors %}
    <div class="panel">
      {{ form.non_field_errors }}
    </div>
  {% endif %}
  {% block contenido %}
    <script>
	    $(document).ready( function () {
	    $("#id_configuracion").attr('class','active');
            var TCargo = $('#lista_autores').dataTable({
              "iDisplayLength": 5,
              "iDisplayStart": 0,
              "sPaginationType": "full_numbers",
              "aLengthMenu": [5, 10, 20, 30, 40, 50],
              "oLanguage": {"sUrl": "/static/js/es.txt"},
              "aoColumns": [
                  {"sClass": "registro center", "sWidth": "1%"},
                  {"sClass": "registro center", "sWidth": "8%"},
                  {"sWidth": "3%", "bSortable": false, "sClass": "center sorting_false", "bSearchable": false}
              ]
            });
        } );
	</script>
        {% load templatag_grupos %}
	<div class='panel panel-default' style='width:90%'>
	<div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Listado de Autores</div>
    <br>
    <div style='width: 60em;'>
    <table class='table table-striped table-hover' id='lista_autores'>
      <thead>
      <tr>
        <th colspan=3>
          {% ifusergroup administrador %}
          <a href='/autores/data'>
            <button class='btn btn-default'>Importar Autores</button>
          </a>
          {% endifusergroup %}
           <a href="/autores/registrar_autor" title='Nuevo'>  
            <button class='btn btn-default'>Registrar Autor</button>
          </a>
        </th>
      </tr>
      <tr style='background-color: #E86639; color:white;'>
        <th style='text-align: left;'><b>Código</b></th>
        <th style='text-align: left;'><b>Autor</b></th>
        <th style='text-align: right;'>Acción</th>
      </tr>
      </thead>
      <tbody>
      {% for au in listar_autores %}
      <tr>
        <td style="text-align: left !important;">{{ au.cod_autor }}</td>
        <td style="text-align: left !important;">{{ au.autor }}</td>
        <td style="text-align: right !important;">
          <a href='{% url "actualizar_autor" au.id %}'>
            <img src='/static/image/editar.png' title='Editar' style="width:30px;height:30px;">
          </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <a onclick="eliminar_data('{{au.id}}', '/autores/eliminar_autor/')">
            <img src='/static/image/eliminar.png' title='Eliminar'>
          </a>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
    </div>
    <br>
    </div>
    {% endblock contenido%}
<!-- ************************************************************* -->

templates/autores/nuevo_autor.html
{% extends "base/base.html" %} <!-- Heredando (Bloque) plantilla index -->

{% block title %}Registrar Autor{% endblock title%} <!--Bloque para definir el título-->


{% block contenido %} <!-- Apertura de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/select2/select2-bootstrap.css">
	
<script src="{{STATIC_URL}}js/select2/select2.js"></script>
<script src="{{STATIC_URL}}js/select2/select2_locale_es.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('#id_autor').alpha({allow:" -"}); //Valida solo valores tipo texto
	    
	// Validamos los campos del formulario
	$("#registrar").click(function(e) {
	   e.preventDefault();  // Para evitar que se envíe por defecto
		    
	    if($('#id_autor').val().trim() == ''){
		bootbox.alert("Rellene el campo de autor", function () {
		$('#id_autor').parent('div').addClass('has-error');
		});
		$('#id_autor').focus();
	    }else{
		$('#form_autor').submit();
		}
	});
	
	$('#volver').click(function(){
	    url = '/autores/listar_autores'
	    window.location = url
	})
	
});
</script>
<body>
    <form method="post" id="form_autor">
	{% csrf_token %}
	<div class='panel panel-default' style='width:60%'>
		    <div class="panel-heading" style='font-size: 20px;font-weight:bold;'>Registrar Autor</div>
		    <br>
	<table style="text-align:center;border-collapse: separate;border-spacing: 5px 15px;">
            <tr>
		<td><input id="id_cod_autor" required name="cod_autor" type="hidden" value='{{num_autores}}'/>
		</td>
	    </tr>
	    <tr>
		<td>Autor:</td>
		<td>
			<input id="id_autor" required name="autor" type="text" />
			<input type='hidden' id="id_user_update" name="user_create" value='{{user.id}}'/>
		</td>
	    </tr>
	    <tr>
		<td colspan='2'>
			<input type="submit" id="registrar" value="Registrar"/>
			<input type="button" id="volver" value="Volver" class="btn btn-primary"/>
		</td>
	    </tr>
	</table>
</div>
    </form>
</body>
</html>
{% endblock contenido %} <!-- Cierre de la carga de datos en el bloque 'contenido' de la plantilla 'base' -->